FROM opencell/wildfly-opencell:7.0.0

COPY ./input-files/war /opt/jboss/wildfly/standalone/deployments
COPY ./input-files/opencell-admin.properties /opt/jboss/wildfly/standalone/configuration/opencell-admin.properties
