FROM opencell/wildfly-opencell:7.0.0

COPY $WORKSPACE/Dock-Build/input-files/war /opt/jboss/wildfly/standalone/deployments
COPY $WORKSPACE/Dock-Build/input-files/opencell-admin.properties /opt/jboss/wildfly/standalone/configuration/opencell-admin.properties
